#Name of the application
spring:
  application:
    name: skillTechnologiesService

#Eureka server url for registering
#This is eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
#register url to server    

instance:
  hostname: localhost

server:
  port: 8930